#!/usr/bin/env python3

import sys 
import re 
import os 

if os.path.isdir(".mite"):
    print("mite-init: error: .mite already exists")
else:
    os.mkdir(".mite")
    print("Initialised empty termite repository in .mite")
