#!/usr/bin/env python3

import sys
import re
import os
import shutil

def is_valid_filename(filename):
    valid_filename = r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$"
    # see if valid_filename matches our filename ()
    return re.match(valid_filename, filename) is not None

if not os.path.exists('.mite'):
    print("mite-add: error: mite repository directory .mite not found")
    sys.exit(1)

filenames = sys.argv[1:]
index_path = ".mite/index"

# it just prepares the files to be committed later 
os.makedirs(index_path, exist_ok=True)

for filename in filenames:
    if not is_valid_filename(filename):
        print(f"mite-add: error: invalid filename '{filename}'")
        continue

    if os.path.isfile(filename):
    # copy that file and its metadata into .mite/index/
        dst = os.path.join(index_path, os.path.basename(filename))
        # copy the the contents from filename into dst 
        shutil.copy2(filename, dst)