#!/usr/bin/env python3


import sys
import os

if len(sys.argv) < 2:
    print("usage: mite-show <commit>:<filename>")
    sys.exit(1)

arg = sys.argv[1]
commit_dir = '.mite/commits'
index_dir = '.mite/index'

if ':' in arg:

    # make sure commit_part and filename are on different sides of the colon
    commit_part, filename = arg.split(':', 1)

    # if commit_part is empty, go into index folder and print the desired file
    if commit_part == '':
        file_path = os.path.join(index_dir, filename)
        if os.path.isfile(file_path):
            with open(file_path, 'r') as file:
                print(file.read(), end='')
        else:
            print(f"mite-show: error: '{filename}' not found in index")
    # else, go into the specified commit folder and print the file
    else:
        file_path = os.path.join(commit_dir, commit_part, filename)
        if os.path.isfile(file_path):
            with open(file_path, 'r') as file:
                print(file.read(), end='')
        elif not os.path.exists(os.path.join(commit_dir, commit_part)):
            print(f"mite-show: error: unknown commit '{commit_part}'")
        else:
            print(f"mite-show: error: '{filename}' not found in commit {commit_part}")


# if argument wasn't inputted properly, give out usage error
else:
    print("usage: mite-show <commit>:<filename>")
    sys.exit(1)
